from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_ROOT = PROJECT_ROOT / "data" / "demo"
TRAIN_DIR = DATA_ROOT / "train"
VAL_DIR = DATA_ROOT / "val"
TEST_DIR = DATA_ROOT / "test"

OUTPUT_ROOT = PROJECT_ROOT / "outputs"
CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"

SEED = 42
DEVICE = "cuda"

BATCH_SIZE = 1
NUM_WORKERS = 0
EPOCHS = 2
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-5

IN_CHANNELS = 3
OUT_CHANNELS = 1
BASE_CHANNELS = 16
DEPTH = 4
PREDICT_RESIDUAL = True

LAMBDA_BRAGG = 1.0
LAMBDA_GRADIENT = 0.2
BRAGG_DISTAL_FRACTION = 0.25

DOSE_NORM_EPS = 1e-8
E0_MIN_MEV = 70.0
E0_MAX_MEV = 250.0

BEV_CROP_SIZE = (64, 64, 64)
USE_BEV_CROP = False

SAVE_EVERY_EPOCH = True
